# coding: utf-8

"""
    Atinary™ Nexus

    As part of Atinary™ Nexus, we offer a downloadable software development kit (SDK) client, which facilitates the access to the application programming interface (API) entry point. This API allows users to manage their project subscriptions and to share files among collaborators involved in the same project(s). The api usage requires an `API KEY`, associated to your Atinary™ Nexus account. You can generate your `API KEY` on your [account information page](https://home.atinary.com/user).  # noqa: E501

    The version of the OpenAPI document: beta
    Contact: support@atinary.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class ProjectDetail(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'project_id': 'str',
        'name': 'str',
        'owner': 'str',
        'members': 'list[str]',
        'files': 'AvailableFilesSummary',
        'description': 'str',
        'creation_date': 'datetime'
    }

    attribute_map = {
        'project_id': 'project_id',
        'name': 'name',
        'owner': 'owner',
        'members': 'members',
        'files': 'files',
        'description': 'description',
        'creation_date': 'creation_date'
    }

    def __init__(self, project_id=None, name=None, owner=None, members=None, files=None, description='', creation_date=None, local_vars_configuration=None):  # noqa: E501
        """ProjectDetail - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._project_id = None
        self._name = None
        self._owner = None
        self._members = None
        self._files = None
        self._description = None
        self._creation_date = None
        self.discriminator = None

        self.project_id = project_id
        self.name = name
        self.owner = owner
        self.members = members
        self.files = files
        if description is not None:
            self.description = description
        self.creation_date = creation_date

    @property
    def project_id(self):
        """Gets the project_id of this ProjectDetail.  # noqa: E501

        ID assigned to the project once created in Atinary™ Nexus  # noqa: E501

        :return: The project_id of this ProjectDetail.  # noqa: E501
        :rtype: str
        """
        return self._project_id

    @project_id.setter
    def project_id(self, project_id):
        """Sets the project_id of this ProjectDetail.

        ID assigned to the project once created in Atinary™ Nexus  # noqa: E501

        :param project_id: The project_id of this ProjectDetail.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and project_id is None:  # noqa: E501
            raise ValueError("Invalid value for `project_id`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                project_id is not None and len(project_id) > 36):
            raise ValueError("Invalid value for `project_id`, length must be less than or equal to `36`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                project_id is not None and len(project_id) < 36):
            raise ValueError("Invalid value for `project_id`, length must be greater than or equal to `36`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                project_id is not None and not re.search(r'^prj_[0-9a-f]{32}$', project_id)):  # noqa: E501
            raise ValueError(r"Invalid value for `project_id`, must be a follow pattern or equal to `/^prj_[0-9a-f]{32}$/`")  # noqa: E501

        self._project_id = project_id

    @property
    def name(self):
        """Gets the name of this ProjectDetail.  # noqa: E501

        Name assigned to the project  # noqa: E501

        :return: The name of this ProjectDetail.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ProjectDetail.

        Name assigned to the project  # noqa: E501

        :param name: The name of this ProjectDetail.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and name is None:  # noqa: E501
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                name is not None and len(name) > 50):
            raise ValueError("Invalid value for `name`, length must be less than or equal to `50`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                name is not None and len(name) < 1):
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                name is not None and not re.search(r'^[ -~]+$', name)):  # noqa: E501
            raise ValueError(r"Invalid value for `name`, must be a follow pattern or equal to `/^[ -~]+$/`")  # noqa: E501

        self._name = name

    @property
    def owner(self):
        """Gets the owner of this ProjectDetail.  # noqa: E501

        User email  # noqa: E501

        :return: The owner of this ProjectDetail.  # noqa: E501
        :rtype: str
        """
        return self._owner

    @owner.setter
    def owner(self, owner):
        """Sets the owner of this ProjectDetail.

        User email  # noqa: E501

        :param owner: The owner of this ProjectDetail.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and owner is None:  # noqa: E501
            raise ValueError("Invalid value for `owner`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                owner is not None and len(owner) > 254):
            raise ValueError("Invalid value for `owner`, length must be less than or equal to `254`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                owner is not None and len(owner) < 4):
            raise ValueError("Invalid value for `owner`, length must be greater than or equal to `4`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                owner is not None and not re.search(r'^(?=[a-zA-Z0-9][a-zA-Z0-9@._%+-]{5,253}$)[a-zA-Z0-9._%+-]{1,64}@(?:(?=[a-zA-Z0-9-]{1,63}\.)[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*\.){1,8}[a-zA-Z]{2,63}$', owner)):  # noqa: E501
            raise ValueError(r"Invalid value for `owner`, must be a follow pattern or equal to `/^(?=[a-zA-Z0-9][a-zA-Z0-9@._%+-]{5,253}$)[a-zA-Z0-9._%+-]{1,64}@(?:(?=[a-zA-Z0-9-]{1,63}\.)[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*\.){1,8}[a-zA-Z]{2,63}$/`")  # noqa: E501

        self._owner = owner

    @property
    def members(self):
        """Gets the members of this ProjectDetail.  # noqa: E501

        A comma separated list of emails.  # noqa: E501

        :return: The members of this ProjectDetail.  # noqa: E501
        :rtype: list[str]
        """
        return self._members

    @members.setter
    def members(self, members):
        """Sets the members of this ProjectDetail.

        A comma separated list of emails.  # noqa: E501

        :param members: The members of this ProjectDetail.  # noqa: E501
        :type: list[str]
        """
        if self.local_vars_configuration.client_side_validation and members is None:  # noqa: E501
            raise ValueError("Invalid value for `members`, must not be `None`")  # noqa: E501

        self._members = members

    @property
    def files(self):
        """Gets the files of this ProjectDetail.  # noqa: E501


        :return: The files of this ProjectDetail.  # noqa: E501
        :rtype: AvailableFilesSummary
        """
        return self._files

    @files.setter
    def files(self, files):
        """Sets the files of this ProjectDetail.


        :param files: The files of this ProjectDetail.  # noqa: E501
        :type: AvailableFilesSummary
        """
        if self.local_vars_configuration.client_side_validation and files is None:  # noqa: E501
            raise ValueError("Invalid value for `files`, must not be `None`")  # noqa: E501

        self._files = files

    @property
    def description(self):
        """Gets the description of this ProjectDetail.  # noqa: E501

        Description of the project.  # noqa: E501

        :return: The description of this ProjectDetail.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ProjectDetail.

        Description of the project.  # noqa: E501

        :param description: The description of this ProjectDetail.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                description is not None and len(description) > 255):
            raise ValueError("Invalid value for `description`, length must be less than or equal to `255`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                description is not None and not re.search(r'^[ -~]*$', description)):  # noqa: E501
            raise ValueError(r"Invalid value for `description`, must be a follow pattern or equal to `/^[ -~]*$/`")  # noqa: E501

        self._description = description

    @property
    def creation_date(self):
        """Gets the creation_date of this ProjectDetail.  # noqa: E501

        Entity creation date (UTC).  # noqa: E501

        :return: The creation_date of this ProjectDetail.  # noqa: E501
        :rtype: datetime
        """
        return self._creation_date

    @creation_date.setter
    def creation_date(self, creation_date):
        """Sets the creation_date of this ProjectDetail.

        Entity creation date (UTC).  # noqa: E501

        :param creation_date: The creation_date of this ProjectDetail.  # noqa: E501
        :type: datetime
        """
        if self.local_vars_configuration.client_side_validation and creation_date is None:  # noqa: E501
            raise ValueError("Invalid value for `creation_date`, must not be `None`")  # noqa: E501

        self._creation_date = creation_date

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProjectDetail):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ProjectDetail):
            return True

        return self.to_dict() != other.to_dict()
